### ISSUE TITLE
Backport python 3.12 for simplejson 3.17.2 

### ISSUE THREAD

**Issue by 0xbe7a** [conda-forge/simplejson-feedstock#38]
### Comment:

Hello,
I would like to bring awslambdaric to Python 3.12. awslambdaric has an upstream dependency on simplejson 3.17.2 which is not available for Python 3.12 atm. Would it be possible to create a new build for 3.17.2 with Python 3.12 to solve this issue? I would be happy to do it by myself, in which case I would add myself as maintainer.

**Comment by ocefpaf** [comment]
I created a maintenance branch in https://github.com/conda-forge/simplejson-feedstock/tree/3.17.x/recipe. That version should be ready for py312.
